### ISSUE TITLE
Hey perfect kernel !!
Keep it up !!

I want to add extra features to this kernel aka docker support by enabling some flags while compiling kernel
But i can't compile it successfully!
Can you guide me to proper env setup for  compilation of used toolchain and base source !
Or if you can directly compile it with enabling those features for me then it would be great
I want to enable these features



### ISSUE THREAD

**Issue by Morakhiyasaiyam** [RuRuTiaSaMa/android_kernel_xiaomi_sm8150#1]
Enable those Generally required option
![IMG_20220212_181447.jpg](https://user-images.githubusercontent.com/19637914/155321926-0c10582e-b1b5-4a7e-9c26-ac74cf84d925.jpg)

**Comment by RuRuTiaSaMa** [comment]
Any clang you can found，no gcc surpport(need patch).Clang is used by default on 4.14 and newer kernel

**Comment by RuRuTiaSaMa** [comment]
https://github.com/nathanchance/android-kernel-clang

**Comment by RuRuTiaSaMa** [comment]
Also，here is no docker test.
see
https://github.com/fbicloud/android_kernel_oneplus_msm8998
https://github.com/cyberknight777/android_kernel_docker/ 
for help or other repositories
You can develop it by yourself，just fork my source，it's easy to get new changes when i done

**Comment by Morakhiyasaiyam** [comment]
Yes i exactly merging cyberknight777 script with base source of yours with depth=1 but after enabling those docker features in utility in menu config i am getting warning and kernel could not compile
So i tried with compiling without any modifications but also getting same warnings and errors and after 5-6 minutes it stop with error

**Comment by RuRuTiaSaMa** [comment]
Just enable the features in deconfig that show "missing" in termux，but，add them into docker's kconfig is better

**Comment by RuRuTiaSaMa** [comment]
By the way，try apply this patch will be better？
https://github.com/fbicloud/android_kernel_oneplus_msm8998/commit/fb7bcc1d0b4f5b8a0526ff43d6357cfa1e63b22e

**Comment by RuRuTiaSaMa** [comment]
Here is guide for run docker on android without vm and chroot
https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27

**Comment by Morakhiyasaiyam** [comment]
> Here is guide for run docker on android without vm and chroot
> https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27

Yes i am doing it after seen this gist
I am compiling for Raphael so how can i patch with 8998 op ?

**Comment by RuRuTiaSaMa** [comment]
> > Here is guide for run docker on android without vm and chroot
> > https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27
> 
> Yes i am doing it after seen this gist I am compiling for Raphael so how can i patch with 8998 op ?

It was a common patch available by the tutorial

**Comment by Morakhiyasaiyam** [comment]
Ok will try in evening

**Comment by Morakhiyasaiyam** [comment]
Hey bro i tried but no luck can you build one for me ?

**Comment by Morakhiyasaiyam** [comment]
Hey bro sorry to mention it again & again but kernel is not building it gets exit while building when its compiling
kernel/built-in.o
Or 
net/built-in.o
I am compiling it for raphael miui 12.6 eu
Can you guide me if i am using wrong branch or what
Or if you can me also give your build script so i can give a look !
Thanks

**Comment by RuRuTiaSaMa** [comment]
> Hey bro sorry to mention it again & again but kernel is not building it gets exit while building when its compiling kernel/built-in.o Or net/built-in.o I am compiling it for raphael miui 12.6 eu Can you guide me if i am using wrong branch or what Or if you can me also give your build script so i can give a look ! Thanks

It can not link without lld when your clang is not a clang that inclde binutils since 4.14.267，lazy to fix that.path your own clang (such as proton clang and azune clang) to override default，then everything will be ok
Don't use default clang in your system ，or try to set linker to lld by "export LD=ld.lld" instead of gnu binutils's gold(the default linker)
